GET http://localhost:8080/movies

###

POST http://localhost:8080/movies
Content-Type: application/json
 
 {  
    "title": "Iron Man",
    "premiere": 2010,
    "genre": "action"
    
 }

###

PUT http://localhost:8080/movies/id
Content-Type: application/json
 
 {  
    "title": "Mary Poppins",
    "premiere": 1965,
    "genre": "musical"
    
    
 }

###

DELETE http://localhost:8080/movies/:id